// Generated by npm run db:types from versioned migrations. Do not edit manually.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type Database = { public: { Tables: {
  opportunities: {
    Row: {
      id: string;
      user_id: string;
      title: string;
      description: string;
      agency: string;
      solicitation_number: string;
      category: string;
      value: number;
      deadline: string;
      status: string;
      winnability_score: number;
      set_aside: string | null;
      naics_code: string | null;
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id?: string;
      user_id?: string;
      title: string;
      description: string;
      agency: string;
      solicitation_number: string;
      category: string;
      value: number;
      deadline: string;
      status?: string;
      winnability_score?: number;
      set_aside?: string | null;
      naics_code?: string | null;
      created_at?: string;
      updated_at?: string;
    };
    Update: {
      id?: string;
      user_id?: string;
      title?: string;
      description?: string;
      agency?: string;
      solicitation_number?: string;
      category?: string;
      value?: number;
      deadline?: string;
      status?: string;
      winnability_score?: number;
      set_aside?: string | null;
      naics_code?: string | null;
      created_at?: string;
      updated_at?: string;
    };
    Relationships: [
      { foreignKeyName: "opportunities_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "users"; referencedColumns: ["id"] },
    ];
  };
  quotes: {
    Row: {
      id: string;
      user_id: string;
      opportunity_id: string;
      quote_number: string;
      title: string;
      status: string;
      line_items: Json;
      subtotal: number;
      tax_rate: number;
      tax_amount: number;
      total: number;
      notes: string | null;
      valid_until: string | null;
      version: number;
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id?: string;
      user_id?: string;
      opportunity_id: string;
      quote_number: string;
      title: string;
      status?: string;
      line_items: Json;
      subtotal?: number;
      tax_rate?: number;
      tax_amount?: number;
      total?: number;
      notes?: string | null;
      valid_until?: string | null;
      version?: number;
      created_at?: string;
      updated_at?: string;
    };
    Update: {
      id?: string;
      user_id?: string;
      opportunity_id?: string;
      quote_number?: string;
      title?: string;
      status?: string;
      line_items?: Json;
      subtotal?: number;
      tax_rate?: number;
      tax_amount?: number;
      total?: number;
      notes?: string | null;
      valid_until?: string | null;
      version?: number;
      created_at?: string;
      updated_at?: string;
    };
    Relationships: [
      { foreignKeyName: "quotes_opportunity_id_user_id_fkey"; columns: ["opportunity_id","user_id"]; isOneToOne: false; referencedRelation: "opportunities"; referencedColumns: ["id","user_id"] },
    ];
  };
  taskpacks: {
    Row: {
      id: string;
      user_id: string;
      opportunity_id: string;
      name: string;
      description: string | null;
      status: string;
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id?: string;
      user_id?: string;
      opportunity_id: string;
      name: string;
      description?: string | null;
      status?: string;
      created_at?: string;
      updated_at?: string;
    };
    Update: {
      id?: string;
      user_id?: string;
      opportunity_id?: string;
      name?: string;
      description?: string | null;
      status?: string;
      created_at?: string;
      updated_at?: string;
    };
    Relationships: [
      { foreignKeyName: "taskpacks_opportunity_id_user_id_fkey"; columns: ["opportunity_id","user_id"]; isOneToOne: false; referencedRelation: "opportunities"; referencedColumns: ["id","user_id"] },
    ];
  };
  tasks: {
    Row: {
      id: string;
      user_id: string;
      opportunity_id: string;
      task_pack_id: string | null;
      title: string;
      description: string | null;
      status: string;
      priority: string;
      assigned_to: string | null;
      due_date: string | null;
      completed_at: string | null;
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id?: string;
      user_id?: string;
      opportunity_id: string;
      task_pack_id?: string | null;
      title: string;
      description?: string | null;
      status?: string;
      priority?: string;
      assigned_to?: string | null;
      due_date?: string | null;
      completed_at?: string | null;
      created_at?: string;
      updated_at?: string;
    };
    Update: {
      id?: string;
      user_id?: string;
      opportunity_id?: string;
      task_pack_id?: string | null;
      title?: string;
      description?: string | null;
      status?: string;
      priority?: string;
      assigned_to?: string | null;
      due_date?: string | null;
      completed_at?: string | null;
      created_at?: string;
      updated_at?: string;
    };
    Relationships: [
      { foreignKeyName: "tasks_assigned_to_fkey"; columns: ["assigned_to"]; isOneToOne: false; referencedRelation: "users"; referencedColumns: ["id"] },
      { foreignKeyName: "tasks_opportunity_id_user_id_fkey"; columns: ["opportunity_id","user_id"]; isOneToOne: false; referencedRelation: "opportunities"; referencedColumns: ["id","user_id"] },
      { foreignKeyName: "tasks_task_pack_id_opportunity_id_user_id_fkey"; columns: ["task_pack_id","opportunity_id","user_id"]; isOneToOne: false; referencedRelation: "taskpacks"; referencedColumns: ["id","opportunity_id","user_id"] },
    ];
  };
}; Views: { [_ in never]: never }; Functions: { [_ in never]: never }; Enums: { [_ in never]: never }; CompositeTypes: { [_ in never]: never } } };
